apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2024-12-12T07:15:06Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: nginx
    version: blue
  name: nginx-service
  namespace: default
  resourceVersion: "34501"
  uid: 527f329f-ed45-4d06-89c4-fcb67929c0a2
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.234.120
  clusterIPs:
  - 34.118.234.120
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30854
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
    version: green
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.122.250.124
      ipMode: VIP
